services:
    app:
        build:
          context: ./docker/php
          dockerfile: Dockerfile
          args:
              - CURRENT_UID=${CURRENT_UID}
        image: test-task
        container_name: ${CONTAINER_PREFIX}-app
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        volumes:
          - ./:/var/www
          - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
          - db
        networks:
          - test-task

    db:
      image: mysql:latest
      restart: unless-stopped
      container_name: ${CONTAINER_PREFIX}-db
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      volumes:
        - ./dbdata:/var/lib/mysql/
        - ./mysql/my.cnf:/etc/mysql/my.cnf
      ports:
          - ${DB_CONTAINER_PORT}:${DB_PORT}
      networks:
          - test-task

    nginx:
        image: nginx:alpine
        container_name:  ${CONTAINER_PREFIX}-nginx
        restart: unless-stopped
        tty: true
        ports:
          - ${NGINX_CONTAINER_PORT}:80
        volumes:
          - ./:/var/www
          - ./docker/nginx:/etc/nginx/conf.d
        networks:
          - test-task

    redis:
        image: redis:latest
        container_name: ${CONTAINER_PREFIX}-redis
        restart: unless-stopped
        ports:
          - ${REDIS_PORT}:6379
        networks:
          - test-task
networks:
    test-task:
        driver: bridge
